//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreTanPhat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class BaiViet
    {

        [Display(Name = "Bài Viết")]
        public int Id_BaiViet { get; set; }

        [Display(Name = "Nhân Viên")]
        public Nullable<int> Id_NhanVien { get; set; }

        [Display(Name = "Tiêu Đề")]
        [Required(ErrorMessage ="Vui lòng nhập tiêu đề")]
        public string TieuDe { get; set; }

        [Display(Name = "Miêu Tả")]
        [Required(ErrorMessage = "Vui lòng nhập miêu tả")]
        public string MieuTaNgan { get; set; }

        [Display(Name = "Lượt Xem")]
        public int LuotXem { get; set; }

        [Display(Name = "Nội Dung")]
        [Required(ErrorMessage = "Vui lòng nhập nội dung")]
        public string NoiDung { get; set; }

        [Display(Name = "Hình Ảnh")]
        public string HinhAnh { get; set; }

        [Display(Name = "Xét Duyệt")]
        public int XetDuyet { get; set; }

        [Display(Name = "Hình Ảnh")]
        public HttpPostedFileBase DuLieuHinhAnh { get; set; }

        [Display(Name = "Nhân Viên")]
        public virtual NhanVien NhanVien { get; set; }
    }
}
