//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreTanPhat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class BinhLuan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BinhLuan()
        {
            this.PhanHoiBinhLuan = new HashSet<PhanHoiBinhLuan>();
        }
        [Display(Name = "Bình Luận")]
        public int ID_BinhLuan { get; set; }

        [Display(Name = "Khách Hàng")]
        public int ID_KhachHang { get; set; }

        [Display(Name = "Sản Phẩm")]
        public Nullable<int> ID_SanPham { get; set; }

        [Display(Name = "Nội Dung")]
        public string NoiDung { get; set; }

        [Display(Name = "Ngày Bình Luận")]
        public System.DateTime NgayBinhLuan { get; set; }

        [Display(Name = "Hình Ảnh")]
        public string HinhAnh { get; set; }

        [Display(Name = "Hiển Thị")]
        public int HienThi { get; set; }

        [Display(Name = "Sao")]
        public Nullable<int> Star { get; set; }

        [Display(Name = "Dữ Liệu Hình Ảnh")]
        public HttpPostedFileBase DuLieuHinhAnh { get; set; }

        [Display(Name = "Khách Hàng")]
        public virtual KhachHang KhachHang { get; set; }

        [Display(Name = "Sản Phẩm")]
        public virtual SanPham SanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        [Display(Name = "Phản Hồi")]
        public virtual ICollection<PhanHoiBinhLuan> PhanHoiBinhLuan { get; set; }
    }
}
