//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreTanPhat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class DanhMucSanPhamCon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhMucSanPhamCon()
        {
            this.SanPham = new HashSet<SanPham>();
        }

        [Display(Name = "Danh Mục Sản Phẩm")]
        public int ID_DMSPC { get; set; }

        [Display(Name = "Danh Mục Sản Phẩm")]
        public int ID_DanhMucSanPham { get; set; }

        [Display(Name = "Tên Danh Mục Sản Phẩm Con")]
        [Required(ErrorMessage = "Vui lòng nhập tên danh mục con")]
        public string TenDMSPC { get; set; }

        [Display(Name = "Tình Trạng")] 
        public int TinhTrangHienThi { get; set; }

        [Display(Name = "Hình Ảnh")]
        public string HinhAnh { get; set; }

        [Display(Name = "Hình Ảnh")]
        public HttpPostedFileBase DuLieuHinhAnh { get; set; }

        [Display(Name = "Danh Mục Sản Phẩm")]
        public virtual DanhMucSanPham DanhMucSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPham { get; set; }
    }
}
