//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreTanPhat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DatHangChiTiet
    {
        [Display(Name = "Đặt Hàng Chi Tiết")]
        public int ID_DatHangChiTiet { get; set; }

        [Display(Name = "Đặt Hàng")]
        public int ID_DatHang { get; set; }

        [Display(Name = "Sản Phẩm")]
        public int ID_SanPham { get; set; }

        [Display(Name = "Đơn Giá")]
        public int DonGia { get; set; }

        [Display(Name = "Số Lượng")]
        public int SoLuong { get; set; }

        [Display(Name = "Tổng Tiền")]
        public int TongTien { get; set; }
    
        [Display(Name ="Đặt Hàng")]
        public virtual DatHang DatHang { get; set; }
        [Display(Name ="Sản Phẩm")]
        public virtual SanPham SanPham { get; set; }
    }
}
