//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreTanPhat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatHang()
        {
            this.DatHangChiTiet = new HashSet<DatHangChiTiet>();
        }

        [Display(Name = "Đặt Hàng")]
        public int ID_DatHang { get; set; }

        [Display(Name = "Khách Hàng")]
        public int ID_KhachHang { get; set; }

        [Display(Name = "Phí Ship")]
        public Nullable<int> PhiShip { get; set; }

        [Display(Name = "Địa Chỉ Giao Hàng")]
        public string DiaChiGiaoHang { get; set; }

        [Display(Name = "Họ Tên")]
        public string HoTenNguoiNhan { get; set; }

        [Display(Name = "Phone")]
        public string SoDienThoai { get; set; }

        [Display(Name = "Ngày Lập Đơn")]
        public System.DateTime NgayLap { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }

        [Display(Name = "Tổng Tiền")]
        public int TongTien { get; set; }

        [Display(Name = "Tình Trạng")]
        public int TinhTrangDonHang { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatHangChiTiet> DatHangChiTiet { get; set; }
    }
}
