//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreTanPhat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DiaChiKhachHang
    {

        [Display(Name = "Địa Chỉ")]
        public int ID_DiaChi { get; set; }

        [Display(Name = "Khách Hàng")]
        public int ID_KhachHang { get; set; }

        [Display(Name = "Tỉnh")]
        public Nullable<int> ID_Tinh { get; set; }

        [Display(Name = "Huyện")]
        public Nullable<int> ID_Huyen { get; set; }

        [Display(Name = "Xã")]
        public Nullable<int> ID_Xa { get; set; }

        [Display(Name = "Địa Chỉ")]
        public string DiaChi { get; set; }

        [Display(Name = "Trạng Thái")]
        public int TrangThai { get; set; }

        [Display(Name = "Huyện")]
        public virtual Huyen Huyen { get; set; }

        [Display(Name = "Khách Hàng")]
        public virtual KhachHang KhachHang { get; set; }

        [Display(Name = "Tỉnh")]
        public virtual Tinh Tinh { get; set; }

        [Display(Name = "Xã")]
        public virtual Xa Xa { get; set; }
    }
}
