//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreTanPhat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.BaiViet = new HashSet<BaiViet>();
            this.PhanHoiBinhLuan = new HashSet<PhanHoiBinhLuan>();
            this.SanPham = new HashSet<SanPham>();
        }

        [Display(Name = "Nhân Viên")]
        public int ID_NhanVien { get; set; }

        [Display(Name = "Tên Nhân Viên")]
        [Required(ErrorMessage ="Vui lòng nhập tên nhân viên")]
        public string TenNhanVien { get; set; }

        [Display(Name = "Địa Chỉ")]
        [Required(ErrorMessage = "Vui lòng nhập địa chỉ")]
        public string DiaChiNhanVien { get; set; }

        [Display(Name = "Năm Sinh")]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Vui lòng chọn năm sinh")]
        public System.DateTime ?NamSinhNhanVien { get; set; }

        [Display(Name = "Giới Tính")]
        [Required(ErrorMessage = "Vui lòng chọn giới tính")]
        public int GioiTinh { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập Gmail")]
        [EmailAddress(ErrorMessage = "Địa chỉ Gmail không đúng")]
        public string GmailNhanVien { get; set; }

        [Display(Name = "Tên Đăng Nhập")]
        [Required(ErrorMessage ="Vui lòng nhập tên đăng nhập")]
        public string TenDangNhapNV { get; set; }

        [Display(Name = "Mật Khẩu")]
        [Required(ErrorMessage ="Vui lòng nhập mật khẩu")]
        //[RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^\da-zA-Z]).{8,15}$", ErrorMessage = "Mật khẩu phải có từ 6 đến 20 ký tự và chứa một ký tự viết hoa, một ký tự viết thường, một chữ số và một ký tự đặc biệt.")]
        [DataType(DataType.Password)]
        public string MatKhauNV { get; set; }

        [Display(Name = "Hỉnh Ảnh")]
        public string HinhAnhNV { get; set; }

        [Display(Name = "Quyền")]
        [Required(ErrorMessage ="Vui lòng chọn quyền")]
        public int QuyenNhanVien { get; set; }

        public HttpPostedFileBase DuLieuHinhAnh { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiViet> BaiViet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanHoiBinhLuan> PhanHoiBinhLuan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPham { get; set; }
    }
    public class LoginNhanVien
    {
        [Display(Name = "Tên Đăng Nhập")]
        public string TenDangNhapNV { get; set; }

        [Display(Name = "Mật Khẩu")]
        [DataType(DataType.Password)]
        public string MatKhauNV { get; set; }
    }
}
