//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreTanPhat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class PhanHoiBinhLuan
    {

        [Display(Name = "Phản Hồi Bình Luận")]
        public int ID_PhanHoiBinhLuan { get; set; }

        [Display(Name = "Bình Luận")]
        public int ID_BinhLuan { get; set; }

        [Display(Name = "Nội Dung")]
        public string NoiDung { get; set; }

        [Display(Name = "Khách Hàng")]
        public Nullable<int> ID_KhachHang { get; set; }

        [Display(Name = "Nhân Viên")]
        public Nullable<int> ID_NhanVien { get; set; }

        [Display(Name = "Hình Ảnh")]
        public string HinhAnh { get; set; }

        [Display(Name = "Ngày Bình Luận")]
        public System.DateTime NgayBinhLuan { get; set; }

        [Display(Name = "Hiển Thị")]
        public int HienThi { get; set; }

        public HttpPostedFileBase DuLieuHinhAnh { get; set; }

        [Display(Name = "Bình Luận")]
        public virtual BinhLuan BinhLuan { get; set; }

        [Display(Name = "Khách Hàng")]
        public virtual KhachHang KhachHang { get; set; }

        [Display(Name = "Nhân Viên")]
        public virtual NhanVien NhanVien { get; set; }
    }
}
