//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreTanPhat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PhiVanChuyen
    {

        [Display(Name = "Phí Vận Chuyển")]
        public int Id_PhiVanChuyen { get; set; }
        public Nullable<int> ID_Tinh { get; set; }
        public Nullable<int> ID_Huyen { get; set; }
        public Nullable<int> ID_Xa { get; set; }

        [Display(Name = "Giá Vận Chuyển")]
        public Nullable<int> GiaVanChuyen { get; set; }

        [Display(Name = "Ghi Chú")]
        public string GhiChu { get; set; }
    

        [Display(Name = "Huyện")]
        [Required(ErrorMessage ="Vui lòng chọn tỉnh")]
        public virtual Huyen Huyen { get; set; }

        [Display(Name = "Tỉnh")]
        [Required(ErrorMessage = "Vui lòng chọn huyện")]
        public virtual Tinh Tinh { get; set; }

        [Display(Name = "Xã")]
        [Required(ErrorMessage = "Vui lòng chọn xã")]
        public virtual Xa Xa { get; set; }
    }
}
