//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreTanPhat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.BinhLuan = new HashSet<BinhLuan>();
            this.DatHangChiTiet = new HashSet<DatHangChiTiet>();
            this.GioHang = new HashSet<GioHang>();
            this.HinhAnhSanPham = new HashSet<HinhAnhSanPham>();
            this.SanPhamLienQuan = new HashSet<SanPhamLienQuan>();
            this.YeuThich = new HashSet<YeuThich>();
        }

        [Display(Name = "Sản Phẩm")]
        public int ID_SanPham { get; set; }

        [Display(Name = "Thương Hiệu")]
        [Required(ErrorMessage = "Vui lòng chọn thương hiệu")]
        public int ID_ThuongHieu { get; set; }

        [Display(Name = "Danh Mục Sản Phẩm Con")]
        [Required(ErrorMessage = "Vui lòng chọn thương hiệu")]
        public int ID_DanhMucSanPhamCon { get; set; }

        [Display(Name = "Nhân Viên")]
        public int ID_NhanVien { get; set; }

        [Display(Name = "Tên Sản Phẩm")]
        [Required(ErrorMessage = "Vui lòng nhập tên sản phẩm")]
        public string TenSanPham { get; set; }

        [Display(Name = "Giá Bán")]
        [Required(ErrorMessage = "Vui lòng nhập giá bán")]
        public int GiaBan { get; set; }

        [Display(Name = "Giá Khuyến Mãi")]
        public Nullable<int> GiaKhuyenMai { get; set; }

        [Display(Name = "Hình Ảnh")]
        public string HinhAnhDaiDien { get; set; }

        [Display(Name = "Mô Tả")]
        [Required(ErrorMessage = "Vui lòng nhập mô tả")]
        public string Motasanpham { get; set; }

        [Display(Name = "Tình Trạng")]
        [Required(ErrorMessage = "Vui lòng chọn tình trạng")]
        public int TinhTrang { get; set; }

        [Display(Name = "Bảo Hành")]
        [Required(ErrorMessage = "Vui lòng chọn bảo hành")]
        public string BaoHanh { get; set; }

        [Display(Name = "Tình Trạng")]
        [Required(ErrorMessage = "Vui lòng chọn tình trạng")]
        public int TinhTrangHienThi { get; set; }

        [Display(Name = "Số Lượng")]
        [Required(ErrorMessage = "Vui lòng nhập số lượng")]
        public int SoLuong { get; set; }

        [Display(Name = "Ngày Cập Nhật")]
        public Nullable<System.DateTime> NgayCapNhat { get; set; }

        [Display(Name = "Sản Phẩm Nổi Bật")]
        public int SanPhamNoiBat { get; set; }

        [Display(Name = "Khuyến Mãi")]
        public string KhuyenMai { get; set; }

        public HttpPostedFileBase DuLieuHinhAnh { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuan { get; set; }
        public virtual DanhMucSanPhamCon DanhMucSanPhamCon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatHangChiTiet> DatHangChiTiet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnhSanPham> HinhAnhSanPham { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual ThuongHieu ThuongHieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamLienQuan> SanPhamLienQuan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuThich> YeuThich { get; set; }
    }
}
