//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreTanPhat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPhamLienQuan
    {
        [Display(Name = "Sản Phẩm Liên Quan")]
        public int ID_SPLQ { get; set; }

        [Display(Name = "Slider")]
        public int ID_Slider { get; set; }

        [Display(Name = "Sản Phẩm")]
        [Required(ErrorMessage = "Vui lòng chọn sản phẩm")]
        public int ID_SanPham { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual Slider Slider { get; set; }
    }
}
