//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreTanPhat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Slider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Slider()
        {
            this.SanPhamLienQuan = new HashSet<SanPhamLienQuan>();
        }

        [Display(Name = "Slider")]
        public int Id_Slider { get; set; }

        [Display(Name = "Tên")]
        [Required(ErrorMessage = "Vui lòng nhập tên Slider")]
        public string TenSilder { get; set; }

        [Display(Name = "Hình Ảnh")]
        public string HinhAnh { get; set; }

        [Display(Name = "Mô Tả")]
        [Required(ErrorMessage = "Vui lòng nhập mô tả")]
        public string MoTa { get; set; }

        [Display(Name = "Vị Trí")]
        [Required(ErrorMessage = "Vui lòng chọn vị trí")]
        public int ViTri { get; set; }

        [Display(Name = "Hiển Thị")]
        [Required(ErrorMessage = "Vui lòng chọn hiển thị")]
        public Nullable<int> HienThi { get; set; }

        public HttpPostedFileBase DuLieuHinhAnh { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamLienQuan> SanPhamLienQuan { get; set; }
    }
}
