//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreTanPhat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopTanPhatEntities : DbContext
    {
        public ShopTanPhatEntities()
            : base("name=ShopTanPhatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaiViet> BaiViet { get; set; }
        public virtual DbSet<BinhLuan> BinhLuan { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<DanhMucSanPham> DanhMucSanPham { get; set; }
        public virtual DbSet<DanhMucSanPhamCon> DanhMucSanPhamCon { get; set; }
        public virtual DbSet<DatHang> DatHang { get; set; }
        public virtual DbSet<DatHangChiTiet> DatHangChiTiet { get; set; }
        public virtual DbSet<DiaChiKhachHang> DiaChiKhachHang { get; set; }
        public virtual DbSet<Footer> Footer { get; set; }
        public virtual DbSet<GioHang> GioHang { get; set; }
        public virtual DbSet<HinhAnhSanPham> HinhAnhSanPham { get; set; }
        public virtual DbSet<Huyen> Huyen { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<MaGiamGia> MaGiamGia { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<PhanHoiBinhLuan> PhanHoiBinhLuan { get; set; }
        public virtual DbSet<PhiVanChuyen> PhiVanChuyen { get; set; }
        public virtual DbSet<SanPham> SanPham { get; set; }
        public virtual DbSet<SanPhamLienQuan> SanPhamLienQuan { get; set; }
        public virtual DbSet<Slider> Slider { get; set; }
        public virtual DbSet<Tinh> Tinh { get; set; }
        public virtual DbSet<ThuongHieu> ThuongHieu { get; set; }
        public virtual DbSet<Xa> Xa { get; set; }
        public virtual DbSet<YeuThich> YeuThich { get; set; }
    }
}
