//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreTanPhat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class ThuongHieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThuongHieu()
        {
            this.SanPham = new HashSet<SanPham>();
        }

        [Display(Name = "Thương Hiệu")]
        public int ID_ThuongHieu { get; set; }

        [Display(Name = "Tên Thương Hiệu")]
        [Required(ErrorMessage = "Vui lòng nhập tên thương hiệu")]
        public string TenThuongHieu { get; set; }

        [Display(Name = "Tình Trạng")]
        [Required(ErrorMessage = "Vui lòng chọn tình trạng")]
        public int TinhTrangHienThi { get; set; }

        [Display(Name = "Hình Ảnh")]
        public string HinhAnh { get; set; }

        public HttpPostedFileBase DuLieuHinhAnh { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPham { get; set; }
    }
}
