//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreTanPhat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Xa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Xa()
        {
            this.DiaChiKhachHang = new HashSet<DiaChiKhachHang>();
            this.PhiVanChuyen = new HashSet<PhiVanChuyen>();
        }
    
        public int xaid { get; set; }

        [Display(Name = "Xã")]
        public string name { get; set; }
        public string loai { get; set; }
        public int maqh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiaChiKhachHang> DiaChiKhachHang { get; set; }
        public virtual Huyen Huyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhiVanChuyen> PhiVanChuyen { get; set; }
    }
}
